{
    "tests": [
        {
            "name": "Public Tests",
            "visibility": "visible",
            "output": "q1 results:\n    q1 - 1 result:\n        \u274c Test case failed\n        Trying:\n            square(1) == 1\n        Expecting:\n            True\n        **********************************************************************\n        Line 1, in q1 0\n        Failed example:\n            square(1) == 1\n        Expected:\n            True\n        Got:\n            False\n\n    q1 - 2 result:\n        \u274c Test case failed\n        Trying:\n            square(0) == 0\n        Expecting:\n            True\n        **********************************************************************\n        Line 1, in q1 1\n        Failed example:\n            square(0) == 0\n        Expected:\n            True\n        Got:\n            False\n\nq2 results:\n    q2 - 1 result:\n        \u274c Test case failed\n        Trying:\n            f = fiberator()\n        Expecting nothing\n        ok\n        Trying:\n            assert next(f) == 0\n        Expecting nothing\n        **********************************************************************\n        Line 2, in q2 0\n        Failed example:\n            assert next(f) == 0\n        Exception raised:\n            Traceback (most recent call last):\n              File \"/usr/lib/python3.10/doctest.py\", line 1350, in __run\n                exec(compile(example.source, filename, \"single\",\n              File \"<doctest q2 0[1]>\", line 1, in <module>\n                assert next(f) == 0\n            TypeError: 'NoneType' object is not an iterator\n        Trying:\n            assert next(f) == 1\n        Expecting nothing\n        **********************************************************************\n        Line 3, in q2 0\n        Failed example:\n            assert next(f) == 1\n        Exception raised:\n            Traceback (most recent call last):\n              File \"/usr/lib/python3.10/doctest.py\", line 1350, in __run\n                exec(compile(example.source, filename, \"single\",\n              File \"<doctest q2 0[2]>\", line 1, in <module>\n                assert next(f) == 1\n            TypeError: 'NoneType' object is not an iterator\n\nq3 results:\n    q3 - 1 result:\n        \u274c Test case failed\n        Trying:\n            len(data['flavor'].unique()) == 4\n        Expecting:\n            True\n        **********************************************************************\n        Line 1, in q3 0\n        Failed example:\n            len(data['flavor'].unique()) == 4\n        Exception raised:\n            Traceback (most recent call last):\n              File \"/usr/lib/python3.10/doctest.py\", line 1350, in __run\n                exec(compile(example.source, filename, \"single\",\n              File \"<doctest q3 0[0]>\", line 1, in <module>\n                len(data['flavor'].unique()) == 4\n            TypeError: 'ellipsis' object is not subscriptable\n\n    q3 - 2 result:\n        \u274c Test case failed\n        Trying:\n            for l in ['chocolate', 'vanilla', 'strawberry', 'mint']:\n                assert l in data['flavor'].unique()\n        Expecting nothing\n        **********************************************************************\n        Line 1, in q3 1\n        Failed example:\n            for l in ['chocolate', 'vanilla', 'strawberry', 'mint']:\n                assert l in data['flavor'].unique()\n        Exception raised:\n            Traceback (most recent call last):\n              File \"/usr/lib/python3.10/doctest.py\", line 1350, in __run\n                exec(compile(example.source, filename, \"single\",\n              File \"<doctest q3 1[0]>\", line 2, in <module>\n                assert l in data['flavor'].unique()\n            TypeError: 'ellipsis' object is not subscriptable\n\n    q3 - 3 result:\n        \u274c Test case failed\n        Trying:\n            assert type(price_by_flavor) == pd.Series\n        Expecting nothing\n        **********************************************************************\n        Line 1, in q3 2\n        Failed example:\n            assert type(price_by_flavor) == pd.Series\n        Exception raised:\n            Traceback (most recent call last):\n              File \"/usr/lib/python3.10/doctest.py\", line 1350, in __run\n                exec(compile(example.source, filename, \"single\",\n              File \"<doctest q3 2[0]>\", line 1, in <module>\n                assert type(price_by_flavor) == pd.Series\n            AssertionError\n\n    q3 - 4 result:\n        \u274c Test case failed\n        Trying:\n            assert len(price_by_flavor) == 4\n        Expecting nothing\n        **********************************************************************\n        Line 1, in q3 3\n        Failed example:\n            assert len(price_by_flavor) == 4\n        Exception raised:\n            Traceback (most recent call last):\n              File \"/usr/lib/python3.10/doctest.py\", line 1350, in __run\n                exec(compile(example.source, filename, \"single\",\n              File \"<doctest q3 3[0]>\", line 1, in <module>\n                assert len(price_by_flavor) == 4\n            TypeError: object of type 'ellipsis' has no len()",
            "status": "failed"
        },
        {
            "name": "q1",
            "score": 0,
            "max_score": 1.0,
            "visibility": "hidden",
            "output": "q1 results:\n    q1 - 1 result:\n        \u274c Test case failed\n        Trying:\n            square(1) == 1\n        Expecting:\n            True\n        **********************************************************************\n        Line 1, in q1 0\n        Failed example:\n            square(1) == 1\n        Expected:\n            True\n        Got:\n            False\n\n    q1 - 2 result:\n        \u274c Test case failed\n        Trying:\n            square(0) == 0\n        Expecting:\n            True\n        **********************************************************************\n        Line 1, in q1 1\n        Failed example:\n            square(0) == 0\n        Expected:\n            True\n        Got:\n            False\n\n    q1 - 3 result:\n        \u274c Test case failed\n        Trying:\n            square(2.5) == 6.25\n        Expecting:\n            True\n        **********************************************************************\n        Line 1, in q1 2\n        Failed example:\n            square(2.5) == 6.25\n        Expected:\n            True\n        Got:\n            False"
        },
        {
            "name": "q2",
            "score": 0,
            "max_score": 1.0,
            "visibility": "hidden",
            "output": "q2 results:\n    q2 - 1 result:\n        \u274c Test case failed\n        Trying:\n            f = fiberator()\n        Expecting nothing\n        ok\n        Trying:\n            assert next(f) == 0\n        Expecting nothing\n        **********************************************************************\n        Line 2, in q2 0\n        Failed example:\n            assert next(f) == 0\n        Exception raised:\n            Traceback (most recent call last):\n              File \"/usr/lib/python3.10/doctest.py\", line 1350, in __run\n                exec(compile(example.source, filename, \"single\",\n              File \"<doctest q2 0[1]>\", line 1, in <module>\n                assert next(f) == 0\n            TypeError: 'NoneType' object is not an iterator\n        Trying:\n            assert next(f) == 1\n        Expecting nothing\n        **********************************************************************\n        Line 3, in q2 0\n        Failed example:\n            assert next(f) == 1\n        Exception raised:\n            Traceback (most recent call last):\n              File \"/usr/lib/python3.10/doctest.py\", line 1350, in __run\n                exec(compile(example.source, filename, \"single\",\n              File \"<doctest q2 0[2]>\", line 1, in <module>\n                assert next(f) == 1\n            TypeError: 'NoneType' object is not an iterator\n\n    q2 - 2 result:\n        \u274c Test case failed\n        Trying:\n            f = fiberator()\n        Expecting nothing\n        ok\n        Trying:\n            assert next(f) == 0\n        Expecting nothing\n        **********************************************************************\n        Line 2, in q2 1\n        Failed example:\n            assert next(f) == 0\n        Exception raised:\n            Traceback (most recent call last):\n              File \"/usr/lib/python3.10/doctest.py\", line 1350, in __run\n                exec(compile(example.source, filename, \"single\",\n              File \"<doctest q2 1[1]>\", line 1, in <module>\n                assert next(f) == 0\n            TypeError: 'NoneType' object is not an iterator\n        Trying:\n            assert next(f) == 1\n        Expecting nothing\n        **********************************************************************\n        Line 3, in q2 1\n        Failed example:\n            assert next(f) == 1\n        Exception raised:\n            Traceback (most recent call last):\n              File \"/usr/lib/python3.10/doctest.py\", line 1350, in __run\n                exec(compile(example.source, filename, \"single\",\n              File \"<doctest q2 1[2]>\", line 1, in <module>\n                assert next(f) == 1\n            TypeError: 'NoneType' object is not an iterator\n        Trying:\n            assert next(f) == 1\n        Expecting nothing\n        **********************************************************************\n        Line 4, in q2 1\n        Failed example:\n            assert next(f) == 1\n        Exception raised:\n            Traceback (most recent call last):\n              File \"/usr/lib/python3.10/doctest.py\", line 1350, in __run\n                exec(compile(example.source, filename, \"single\",\n              File \"<doctest q2 1[3]>\", line 1, in <module>\n                assert next(f) == 1\n            TypeError: 'NoneType' object is not an iterator\n        Trying:\n            assert next(f) == 2\n        Expecting nothing\n        **********************************************************************\n        Line 5, in q2 1\n        Failed example:\n            assert next(f) == 2\n        Exception raised:\n            Traceback (most recent call last):\n              File \"/usr/lib/python3.10/doctest.py\", line 1350, in __run\n                exec(compile(example.source, filename, \"single\",\n              File \"<doctest q2 1[4]>\", line 1, in <module>\n                assert next(f) == 2\n            TypeError: 'NoneType' object is not an iterator\n        Trying:\n            assert next(f) == 3\n        Expecting nothing\n        **********************************************************************\n        Line 6, in q2 1\n        Failed example:\n            assert next(f) == 3\n        Exception raised:\n            Traceback (most recent call last):\n              File \"/usr/lib/python3.10/doctest.py\", line 1350, in __run\n                exec(compile(example.source, filename, \"single\",\n              File \"<doctest q2 1[5]>\", line 1, in <module>\n                assert next(f) == 3\n            TypeError: 'NoneType' object is not an iterator\n        Trying:\n            assert next(f) == 5\n        Expecting nothing\n        **********************************************************************\n        Line 7, in q2 1\n        Failed example:\n            assert next(f) == 5\n        Exception raised:\n            Traceback (most recent call last):\n              File \"/usr/lib/python3.10/doctest.py\", line 1350, in __run\n                exec(compile(example.source, filename, \"single\",\n              File \"<doctest q2 1[6]>\", line 1, in <module>\n                assert next(f) == 5\n            TypeError: 'NoneType' object is not an iterator\n        Trying:\n            assert next(f) == 8\n        Expecting nothing\n        **********************************************************************\n        Line 8, in q2 1\n        Failed example:\n            assert next(f) == 8\n        Exception raised:\n            Traceback (most recent call last):\n              File \"/usr/lib/python3.10/doctest.py\", line 1350, in __run\n                exec(compile(example.source, filename, \"single\",\n              File \"<doctest q2 1[7]>\", line 1, in <module>\n                assert next(f) == 8\n            TypeError: 'NoneType' object is not an iterator\n        Trying:\n            assert next(f) == 13\n        Expecting nothing\n        **********************************************************************\n        Line 9, in q2 1\n        Failed example:\n            assert next(f) == 13\n        Exception raised:\n            Traceback (most recent call last):\n              File \"/usr/lib/python3.10/doctest.py\", line 1350, in __run\n                exec(compile(example.source, filename, \"single\",\n              File \"<doctest q2 1[8]>\", line 1, in <module>\n                assert next(f) == 13\n            TypeError: 'NoneType' object is not an iterator\n        Trying:\n            assert next(f) == 21\n        Expecting nothing\n        **********************************************************************\n        Line 10, in q2 1\n        Failed example:\n            assert next(f) == 21\n        Exception raised:\n            Traceback (most recent call last):\n              File \"/usr/lib/python3.10/doctest.py\", line 1350, in __run\n                exec(compile(example.source, filename, \"single\",\n              File \"<doctest q2 1[9]>\", line 1, in <module>\n                assert next(f) == 21\n            TypeError: 'NoneType' object is not an iterator"
        },
        {
            "name": "q3",
            "score": 0,
            "max_score": 1.0,
            "visibility": "hidden",
            "output": "q3 results:\n    q3 - 1 result:\n        \u274c Test case failed\n        Trying:\n            len(data['flavor'].unique()) == 4\n        Expecting:\n            True\n        **********************************************************************\n        Line 1, in q3 0\n        Failed example:\n            len(data['flavor'].unique()) == 4\n        Exception raised:\n            Traceback (most recent call last):\n              File \"/usr/lib/python3.10/doctest.py\", line 1350, in __run\n                exec(compile(example.source, filename, \"single\",\n              File \"<doctest q3 0[0]>\", line 1, in <module>\n                len(data['flavor'].unique()) == 4\n            TypeError: 'ellipsis' object is not subscriptable\n\n    q3 - 2 result:\n        \u274c Test case failed\n        Trying:\n            for l in ['chocolate', 'vanilla', 'strawberry', 'mint']:\n                assert l in data['flavor'].unique()\n        Expecting nothing\n        **********************************************************************\n        Line 1, in q3 1\n        Failed example:\n            for l in ['chocolate', 'vanilla', 'strawberry', 'mint']:\n                assert l in data['flavor'].unique()\n        Exception raised:\n            Traceback (most recent call last):\n              File \"/usr/lib/python3.10/doctest.py\", line 1350, in __run\n                exec(compile(example.source, filename, \"single\",\n              File \"<doctest q3 1[0]>\", line 2, in <module>\n                assert l in data['flavor'].unique()\n            TypeError: 'ellipsis' object is not subscriptable\n\n    q3 - 3 result:\n        \u274c Test case failed\n        Trying:\n            assert type(price_by_flavor) == pd.Series\n        Expecting nothing\n        **********************************************************************\n        Line 1, in q3 2\n        Failed example:\n            assert type(price_by_flavor) == pd.Series\n        Exception raised:\n            Traceback (most recent call last):\n              File \"/usr/lib/python3.10/doctest.py\", line 1350, in __run\n                exec(compile(example.source, filename, \"single\",\n              File \"<doctest q3 2[0]>\", line 1, in <module>\n                assert type(price_by_flavor) == pd.Series\n            AssertionError\n\n    q3 - 4 result:\n        \u274c Test case failed\n        Trying:\n            assert len(price_by_flavor) == 4\n        Expecting nothing\n        **********************************************************************\n        Line 1, in q3 3\n        Failed example:\n            assert len(price_by_flavor) == 4\n        Exception raised:\n            Traceback (most recent call last):\n              File \"/usr/lib/python3.10/doctest.py\", line 1350, in __run\n                exec(compile(example.source, filename, \"single\",\n              File \"<doctest q3 3[0]>\", line 1, in <module>\n                assert len(price_by_flavor) == 4\n            TypeError: object of type 'ellipsis' has no len()\n\n    q3 - 5 result:\n        \u274c Test case failed\n        Trying:\n            np.isclose(price_by_flavor['chocolate'], 3.33333333)\n        Expecting:\n            True\n        **********************************************************************\n        Line 1, in q3 4\n        Failed example:\n            np.isclose(price_by_flavor['chocolate'], 3.33333333)\n        Exception raised:\n            Traceback (most recent call last):\n              File \"/usr/lib/python3.10/doctest.py\", line 1350, in __run\n                exec(compile(example.source, filename, \"single\",\n              File \"<doctest q3 4[0]>\", line 1, in <module>\n                np.isclose(price_by_flavor['chocolate'], 3.33333333)\n            TypeError: 'ellipsis' object is not subscriptable\n\n    q3 - 6 result:\n        \u274c Test case failed\n        Trying:\n            np.isclose(price_by_flavor['mint'], 4.5)\n        Expecting:\n            True\n        **********************************************************************\n        Line 1, in q3 5\n        Failed example:\n            np.isclose(price_by_flavor['mint'], 4.5)\n        Exception raised:\n            Traceback (most recent call last):\n              File \"/usr/lib/python3.10/doctest.py\", line 1350, in __run\n                exec(compile(example.source, filename, \"single\",\n              File \"<doctest q3 5[0]>\", line 1, in <module>\n                np.isclose(price_by_flavor['mint'], 4.5)\n            TypeError: 'ellipsis' object is not subscriptable\n\n    q3 - 7 result:\n        \u274c Test case failed\n        Trying:\n            np.isclose(price_by_flavor['strawberry'], 3)\n        Expecting:\n            True\n        **********************************************************************\n        Line 1, in q3 6\n        Failed example:\n            np.isclose(price_by_flavor['strawberry'], 3)\n        Exception raised:\n            Traceback (most recent call last):\n              File \"/usr/lib/python3.10/doctest.py\", line 1350, in __run\n                exec(compile(example.source, filename, \"single\",\n              File \"<doctest q3 6[0]>\", line 1, in <module>\n                np.isclose(price_by_flavor['strawberry'], 3)\n            TypeError: 'ellipsis' object is not subscriptable\n\n    q3 - 8 result:\n        \u274c Test case failed\n        Trying:\n            np.isclose(price_by_flavor['vanilla'], 1.75)\n        Expecting:\n            True\n        **********************************************************************\n        Line 1, in q3 7\n        Failed example:\n            np.isclose(price_by_flavor['vanilla'], 1.75)\n        Exception raised:\n            Traceback (most recent call last):\n              File \"/usr/lib/python3.10/doctest.py\", line 1350, in __run\n                exec(compile(example.source, filename, \"single\",\n              File \"<doctest q3 7[0]>\", line 1, in <module>\n                np.isclose(price_by_flavor['vanilla'], 1.75)\n            TypeError: 'ellipsis' object is not subscriptable"
        }
    ]
}